# Generated by Django 3.2 on 2023-03-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settings',
            table='tbl_setting',
        ),
    ]
