# Generated by Django 3.2 on 2023-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departement', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
    ]
