# Generated by Django 3.2 on 2023-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_column='nama_file', max_length=255)),
                ('file', models.FileField(db_column='file_rat', upload_to='dokumen/file_rat')),
            ],
        ),
    ]
