# Generated by Django 3.2 on 2023-03-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simpanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_simpanan', models.CharField(db_column='jns_simpanan', max_length=30)),
                ('jumlah', models.BigIntegerField()),
                ('tampil', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=2)),
                ('keterangan', models.CharField(db_column='ket', max_length=255)),
            ],
        ),
    ]
