# Generated by Django 3.2 on 2023-03-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='simpanan',
            table='jns_simpanan',
        ),
    ]
