# Generated by Django 3.2 on 2023-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0002_transaksisetoransimpanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksisetoransimpanan',
            name='jumlah',
            field=models.FloatField(verbose_name='Jumlah Simpanan'),
        ),
    ]
