# Generated by Django 3.2 on 2023-05-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0003_alter_transaksisetoransimpanan_jumlah'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaksisetoransimpanan',
            table='trans_sp',
        ),
    ]
