# Generated by Django 3.2 on 2023-05-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0004_alter_transaksisetoransimpanan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaksisetoransimpanan',
            table='tbl_trans_sp',
        ),
    ]
