# Generated by Django 3.2 on 2023-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_aktiva', models.CharField(db_column='kd_aktiva', max_length=5)),
                ('jenis_transaksi', models.CharField(db_column='jns_trans', max_length=50)),
                ('akun', models.CharField(choices=[('Aktiva', 'AKTIVA'), ('Pasiva', 'PASIVA')], max_length=15, null=True)),
                ('laba_rugi', models.CharField(choices=[('PENDAPATAN', 'PENDAPATAN'), ('HPP', 'HPP'), ('BIAYA', 'BIAYA')], max_length=15, null=True)),
                ('pemasukan', models.CharField(choices=[('Y', 'YA'), ('N', 'TIDAK')], max_length=1, null=True)),
                ('pengeluaran', models.CharField(choices=[('Y', 'YA'), ('N', 'TIDAK')], max_length=1, null=True)),
                ('aktif', models.CharField(choices=[('Y', 'YA'), ('N', 'TIDAK')], max_length=1)),
            ],
        ),
    ]
