# Generated by Django 3.2 on 2023-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_alter_akun_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='laba_rugi',
            field=models.CharField(choices=[('PENDAPATAN', 'PENDAPATAN'), ('HPP', 'HPP'), ('BIAYA', 'BIAYA'), ('PINJAMAN', 'PINJAMAN')], max_length=15, null=True),
        ),
    ]
