# Generated by Django 3.2 on 2023-03-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_alter_akun_laba_rugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angsurang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.IntegerField(db_column='ket')),
                ('aktif', models.CharField(choices=[('Y', 'YA'), ('N', 'TIDAK')], max_length=2)),
            ],
        ),
    ]
