# Generated by Django 3.2 on 2023-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(db_column='ket', max_length=255)),
                ('nama', models.CharField(db_column='nm_barang', max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('merek', models.CharField(db_column='merk', max_length=50)),
                ('harga', models.FloatField()),
                ('jumlah_barang', models.IntegerField(db_column='jml_brg')),
            ],
            options={
                'db_table': 'tbl_barang',
            },
        ),
    ]
