# Generated by Django 3.2 on 2023-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tempat_lahir',
            field=models.CharField(db_column='tmp_lahir', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='jenis_kelamin',
            field=models.CharField(db_column='jk', max_length=2, null=True),
        ),
    ]
