# Generated by Django 3.2 on 2023-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20230318_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tanggal_lahir',
            field=models.DateField(db_column='tgl_lahir', null=True),
        ),
    ]
