# Generated by Django 3.2 on 2023-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='agama',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='aktif',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='departement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='identitas',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='jabatan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='kota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='nomor_telpon',
            field=models.CharField(blank=True, db_column='notelp', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
