# Generated by Django 3.2 on 2023-03-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20230319_2020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='tbl_anggota',
        ),
    ]
