# Generated by Django 3.2 on 2023-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('aktif', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=2)),
                ('simpanan', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_simpan', max_length=2)),
                ('penarikan', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_penarikan', max_length=2)),
                ('bayar', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_bayar', max_length=2)),
                ('pemasukan', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_pemasukan', max_length=2)),
                ('pengeluaran', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_pengeluaran', max_length=2)),
                ('transfer', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_transfer', max_length=2)),
            ],
            options={
                'db_table': 'nama_kas_tbl',
            },
        ),
    ]
