# Generated by Django 3.2 on 2023-03-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kas',
            name='transfer',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], db_column='tmpl_transfer', max_length=2),
        ),
    ]
